apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb
  name: metallb-network
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.219.150-192.168.219.160

